### ISSUE TITLE
smc line 229

### ISSUE THREAD

**Issue by dionman** [Networks-Learning/hdhp.py#2]
hi, thanks for sharing the code!

if self.num_events >= 1 and u_n in self.time_previous_user_event and \
                self.time_previous_user_event[u_n] > 0

is the second condition in the if statement correct? If I understand correctly, time_previous_user_event list is populated by timestamps.

**Comment by harrymvr** [comment]
Thanks for catching this. On a first read, it seems that you are right. I looked at my private repo that I used before publishing, and this is probably an artifact of when `time_previous_user_event` used to be a dictionary. Is line 231 regularly not executed?

**Comment by dionman** [comment]
Second condition was false (apart from user with id=0)
